name: CD DevOps 2025

on:
  workflow_run:
    workflows: ["CI DevOps 2025"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto-increment patch version in pom.xml
        id: versioning
        run: |
          FILE=simple-api/pom.xml

          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f $FILE)
          echo "Version actuelle : $CURRENT_VERSION"

          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-SNAPSHOT//')
          MAJOR=$(echo $BASE_VERSION | cut -d. -f1)
          MINOR=$(echo $BASE_VERSION | cut -d. -f2)
          PATCH=$(echo $BASE_VERSION | cut -d. -f3)

          NEXT_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEXT_PATCH-SNAPSHOT"
          echo "Nouvelle version : $NEW_VERSION"

          # Met à jour le pom.xml
          sed -i "s/<version>$CURRENT_VERSION<\/version>/<version>$NEW_VERSION<\/version>/" $FILE

          echo "IMAGE_TAG=$NEW_VERSION" >> $GITHUB_ENV

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ env.IMAGE_TAG }}
          push: true

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ env.IMAGE_TAG }}
          push: true

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-http:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-http:${{ env.IMAGE_TAG }}
          push: true
