name: CI DevOps 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checfy sonar:sonar -Dsonar.projectKey=SamyBouaissa_tp-devops-correction-docker -Dsonar.organization=samybouaissa -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
