name: CI DevOps 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and test with Maven
        working-directory: simple-api
        run: mvn clean verify

      - name: SonarCloud analysis
        working-directory: simple-api
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=SamyBouaissa_tp-devops-correction-docker -Dsonar.organization=samybouaissa -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
